name: CI
on: [push]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        engines: ['engine1', 'engine2', 'engine3', 'engine4', 'engine5']
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.13.0

      - name: Build and run tests
        working-directory: './engines/${{ matrix.engines }}'
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
          bundle exec rails db:setup
          bundle exec rspec
